//! A sweep, packaged as one file you can send someone.
//!
//! The situation this exists for: the repo owner has no API budget, someone
//! else does. They clone, add their own key, run one command, and send back a
//! single file. Nothing of theirs is committed and no credential changes
//! hands.
//!
//! Markdown wrapping a JSON block, rather than one or the other. The person
//! sending it should be able to open the file and see exactly what they are
//! about to share — a result they cannot read is a result they have to take on
//! trust, and they are the one taking the risk. The embedded JSON is what
//! makes it comparable on the other end, so the same file serves both.

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use trace_core::error::{Error, Result};
use trace_core::event::Body;
use trace_core::hash::hash_chunks;

use crate::result::{aggregate, Aggregate, TaskResult};
use crate::sweep::{read_results, SweepManifest};
use crate::task::Task;

/// Everything needed to interpret a run someone else performed.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Bundle {
    pub format: String,
    pub manifest: SweepManifest,
    pub aggregate: Aggregate,
    pub rows: Vec<TaskResult>,
    /// Hash of the task set that was run.
    ///
    /// Without this a returned result cannot be compared to anything: the same
    /// pass rate against a different set of tasks is a different number
    /// wearing the same clothes.
    pub task_set_hash: String,
    pub task_ids: Vec<String>,
    /// Where the numbers came from, so a surprising result can be attributed
    /// to a machine rather than to the model.
    pub environment: BTreeMap<String, String>,
    /// Short excerpts from runs that failed. Successes are not interesting;
    /// failures are the whole reason to look.
    pub failures: Vec<FailureExcerpt>,
}

pub const FORMAT: &str = "trace-bundle-v1";

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct FailureExcerpt {
    pub task_id: String,
    pub repeat: u32,
    pub turns: u64,
    pub abort_reason: Option<String>,
    pub error: Option<String>,
    /// The last few tool calls and their results, trimmed.
    pub tail: Vec<String>,
    pub verify_output: String,
}

/// How many trailing tool exchanges to keep from a failed run.
const TAIL_TURNS: usize = 6;
/// Per-field trim, so one runaway command cannot make the bundle unsendable.
const EXCERPT_LIMIT: usize = 1200;

impl Bundle {
    /// Build a bundle from a finished sweep directory.
    ///
    /// `available` is the task set in the current checkout. Only the tasks the
    /// sweep actually ran contribute to the hash — hashing everything present
    /// would let a bundle claim a task set it never touched, and the claim
    /// would be believed on the other end.
    pub fn from_sweep(dir: &Path, available: &[Task]) -> Result<Bundle> {
        let manifest: SweepManifest = read_json(&dir.join("manifest.json"))?;
        let rows = read_results(&dir.join("results.jsonl"))?;
        let aggregate = aggregate(&manifest.model, &rows, manifest.repeats as usize);

        let ran: Vec<Task> = manifest
            .task_ids
            .iter()
            .filter_map(|id| available.iter().find(|t| &t.id == id).cloned())
            .collect();

        if ran.len() != manifest.task_ids.len() {
            let missing: Vec<&String> = manifest
                .task_ids
                .iter()
                .filter(|id| !available.iter().any(|t| &&t.id == id))
                .collect();
            return Err(Error::other(format!(
                "this sweep ran tasks that are not in the current checkout: {missing:?}. \
                 Bundling anyway would produce a task-set hash for a set that was never run, \
                 and the result would be compared against the wrong thing."
            )));
        }

        let failures = rows
            .iter()
            .filter(|r| !r.passed)
            .map(|r| excerpt(r, dir))
            .collect();

        Ok(Bundle {
            format: FORMAT.to_string(),
            task_set_hash: task_set_hash(&ran),
            task_ids: ran.iter().map(|t| t.id.clone()).collect(),
            environment: environment(),
            manifest,
            aggregate,
            rows,
            failures,
        })
    }

    /// Render the shareable file.
    pub fn to_markdown(&self) -> String {
        let a = &self.aggregate;
        let mut s = String::new();

        s.push_str("# TRACE benchmark results\n\n");
        s.push_str(
            "Generated by `trace bench`. Send this file back to whoever asked for it.\n\
             It contains no credentials — see \"What is in this file\" at the bottom.\n\n",
        );

        s.push_str("## Summary\n\n");
        s.push_str("| | |\n|---|---|\n");
        s.push_str(&format!("| model | `{}` |\n", a.model));
        s.push_str(&format!(
            "| tasks | {} x {} repeats = {} runs |\n",
            a.tasks, a.repeats, a.runs
        ));
        s.push_str(&format!(
            "| **pass rate** | **{:.1}%** (sigma {:.1} points) |\n",
            a.pass_rate * 100.0,
            a.pass_rate_sigma * 100.0
        ));
        s.push_str(&format!("| mean turns | {:.1} |\n", a.mean_turns));
        s.push_str(&format!(
            "| tokens | {} in / {} out ({} cached) |\n",
            a.tokens.input, a.tokens.output, a.tokens.cached_input
        ));
        s.push_str(&format!(
            "| cache hit | {:.1}% |\n",
            a.cache_hit_rate * 100.0
        ));
        s.push_str(&format!(
            "| cost | ${:.4} total, ${:.4} per run |\n",
            a.total_usd, a.usd_per_run
        ));
        s.push_str(&format!(
            "| harness commit | `{}` |\n",
            self.manifest.harness_commit
        ));
        s.push_str(&format!(
            "| config hash | `{}` |\n",
            short(&self.manifest.config_hash)
        ));
        s.push_str(&format!(
            "| task set hash | `{}` |\n",
            short(&self.task_set_hash)
        ));

        if a.harness_errors > 0 {
            s.push_str(&format!(
                "\n> **{} run(s) failed inside the harness** and were excluded from the pass \
                 rate. The number above describes fewer runs than were requested.\n",
                a.harness_errors
            ));
        }
        if !a.flaky_task_ids.is_empty() {
            s.push_str(&format!(
                "\n> **Flaky:** {} — passed on some repeats and failed on others.\n",
                a.flaky_task_ids.join(", ")
            ));
        }

        s.push_str("\n## Per task\n\n");
        s.push_str("| task | passed | turns (mean) | notes |\n|---|---|---|---|\n");

        let mut ids: Vec<&str> = self.rows.iter().map(|r| r.task_id.as_str()).collect();
        ids.sort();
        ids.dedup();
        for id in ids {
            let runs: Vec<&TaskResult> = self.rows.iter().filter(|r| r.task_id == id).collect();
            let passed = runs.iter().filter(|r| r.passed).count();
            let turns = runs.iter().map(|r| r.turns as f64).sum::<f64>() / runs.len().max(1) as f64;
            let note = if runs.iter().any(|r| r.error.is_some()) {
                "harness error"
            } else if passed == 0 {
                "failed every repeat"
            } else if passed < runs.len() {
                "flaky"
            } else {
                ""
            };
            s.push_str(&format!(
                "| `{id}` | {passed}/{} | {turns:.1} | {note} |\n",
                runs.len()
            ));
        }

        if !self.failures.is_empty() {
            s.push_str("\n## Failures\n\n");
            s.push_str(
                "Trimmed tails of the runs that did not pass. This is the part worth reading.\n\n",
            );
            for f in &self.failures {
                s.push_str(&format!("### `{}` repeat {}\n\n", f.task_id, f.repeat));
                s.push_str(&format!("- turns: {}\n", f.turns));
                if let Some(r) = &f.abort_reason {
                    s.push_str(&format!("- aborted: {r}\n"));
                }
                if let Some(e) = &f.error {
                    s.push_str(&format!("- harness error: {e}\n"));
                }
                if !f.verify_output.trim().is_empty() {
                    s.push_str("\n```\n");
                    s.push_str(f.verify_output.trim());
                    s.push_str("\n```\n");
                }
                if !f.tail.is_empty() {
                    s.push_str("\n<details><summary>last few tool calls</summary>\n\n```\n");
                    for line in &f.tail {
                        s.push_str(line);
                        s.push('\n');
                    }
                    s.push_str("```\n\n</details>\n");
                }
                s.push('\n');
            }
        }

        s.push_str("\n## Environment\n\n");
        for (k, v) in &self.environment {
            s.push_str(&format!("- {k}: `{v}`\n"));
        }

        s.push_str("\n## What is in this file\n\n");
        s.push_str(
            "- Pass/fail results, token counts, timings, and cost for each run.\n\
             - Trimmed output from runs that failed.\n\
             - The model name, harness commit, and config hash, so the numbers are attributable.\n\n\
             It does **not** contain your API key. The harness never writes credentials to a \
             log — tool processes run with a scrubbed environment, and every line is redacted \
             on its way to disk. The bundle is additionally scanned for key-shaped strings \
             before it is written, and refuses to be created if any are found.\n\n\
             You are welcome to read the whole thing before sending it.\n",
        );

        s.push_str("\n## Machine-readable\n\n");
        s.push_str("Do not edit. Parsed on import.\n\n```json\n");
        s.push_str(&serde_json::to_string_pretty(self).unwrap_or_default());
        s.push_str("\n```\n");

        s
    }

    /// Recover a bundle from a rendered file.
    pub fn from_markdown(text: &str) -> Result<Bundle> {
        let start = text
            .find("```json")
            .ok_or_else(|| Error::other("no machine-readable block; is this a trace bundle?"))?;
        let body = &text[start + "```json".len()..];
        let end = body
            .find("```")
            .ok_or_else(|| Error::other("machine-readable block is not terminated"))?;

        let bundle: Bundle = serde_json::from_str(body[..end].trim())
            .map_err(|e| Error::other(format!("bundle is not readable: {e}")))?;

        if bundle.format != FORMAT {
            return Err(Error::other(format!(
                "bundle format is {:?}, expected {FORMAT:?}",
                bundle.format
            )));
        }
        Ok(bundle)
    }

    pub fn load(path: &Path) -> Result<Bundle> {
        let text = std::fs::read_to_string(path).map_err(|e| Error::io(path, e))?;
        Bundle::from_markdown(&text)
    }

    /// Is this bundle comparable to a local sweep of `tasks`?
    ///
    /// Comparing pass rates across different task sets produces a number that
    /// looks meaningful and is not.
    pub fn matches_task_set(&self, tasks: &[Task]) -> bool {
        self.task_set_hash == task_set_hash(tasks)
    }
}

/// Identity of a task set: ids plus the bytes that define each task.
///
/// Content, not just names. A task whose verification was quietly loosened
/// keeps its id, and a comparison against it would be meaningless in a way
/// nobody would notice.
pub fn task_set_hash(tasks: &[Task]) -> String {
    let mut parts: Vec<Vec<u8>> = Vec::new();
    let mut sorted: Vec<&Task> = tasks.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    for t in sorted {
        parts.push(t.id.as_bytes().to_vec());
        parts.push(t.prompt.as_bytes().to_vec());
        if let Ok(v) = std::fs::read(t.verify_script()) {
            parts.push(v);
        }
    }
    hash_chunks(parts.iter().map(|v| v.as_slice()))
}

fn excerpt(row: &TaskResult, dir: &Path) -> FailureExcerpt {
    let mut tail = Vec::new();

    if let Ok(outcome) = trace_core::log::read(Path::new(&row.trajectory)) {
        let exchanges: Vec<String> = outcome
            .events
            .iter()
            .filter_map(|e| match &e.body {
                Body::ToolCall(c) => Some(format!(
                    "$ {}",
                    trim(
                        c.args
                            .get("cmd")
                            .and_then(|v| v.as_str())
                            .unwrap_or("<no cmd>")
                    )
                )),
                Body::ToolResult(r) => {
                    Some(format!("  exit {} | {}", r.exit_code, trim(&r.output)))
                }
                Body::ModelResponse(m) if !m.message.content.is_empty() => {
                    Some(format!("> {}", trim(&m.message.content)))
                }
                _ => None,
            })
            .collect();

        let start = exchanges.len().saturating_sub(TAIL_TURNS * 2);
        tail = exchanges[start..].to_vec();
    }

    let verify_output = std::fs::read_to_string(
        dir.join(format!("{}.r{}", row.task_id, row.repeat))
            .join("verify.log"),
    )
    .unwrap_or_default();

    FailureExcerpt {
        task_id: row.task_id.clone(),
        repeat: row.repeat,
        turns: row.turns,
        abort_reason: row.abort_reason.map(|r| format!("{r:?}")),
        error: row.error.clone(),
        tail,
        verify_output: trim(&verify_output),
    }
}

fn trim(s: &str) -> String {
    let s = s.trim();
    if s.len() <= EXCERPT_LIMIT {
        return s.replace('\r', "");
    }
    let mut cut = EXCERPT_LIMIT;
    while cut > 0 && !s.is_char_boundary(cut) {
        cut -= 1;
    }
    format!("{}\n[... trimmed ...]", &s[..cut])
}

fn short(hash: &str) -> &str {
    &hash[..12.min(hash.len())]
}

/// Facts about the machine, so a surprising number can be attributed.
///
/// Deliberately coarse. Enough to explain a difference, not enough to
/// fingerprint whoever ran it — they are doing a favour, not filing a report.
fn environment() -> BTreeMap<String, String> {
    let mut env = BTreeMap::new();
    env.insert("os".into(), std::env::consts::OS.into());
    env.insert("arch".into(), std::env::consts::ARCH.into());
    env.insert(
        "trace_version".into(),
        env!("CARGO_PKG_VERSION").to_string(),
    );
    env
}

fn read_json<T: for<'de> Deserialize<'de>>(path: &Path) -> Result<T> {
    let src = std::fs::read_to_string(path).map_err(|e| Error::io(path, e))?;
    serde_json::from_str(&src).map_err(|e| Error::other(format!("{}: {e}", path.display())))
}
